name: build

on:
  workflow_dispatch:

env:
  LIGHTPANDA_DISABLE_TELEMETRY: true

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            target_os: linux
          - os: ubuntu-22.04-arm
            arch: aarch64
            target_os: linux
          - os: macos-14
            arch: aarch64
            target_os: macos

    name: ${{ matrix.target_os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/checkout@v6
        with:
          repository: 'lexiforest/curl-impersonate'
          path: curl-impersonate

      - uses: ./.github/actions/install
        with:
          os: ${{ matrix.target_os }}
          arch: ${{ matrix.arch }}
          curl-impersonate: curl-impersonate

      - name: v8 snapshot
        run: zig build -Dprebuilt_v8_path=v8/libc_v8.a -Doptimize=ReleaseFast -Dcurl_impersonate_path=.curl-impersonate snapshot_creator -- src/snapshot.bin

      - name: build
        run: zig build -Dsnapshot_path=../../snapshot.bin -Dprebuilt_v8_path=v8/libc_v8.a -Doptimize=ReleaseFast -Dcurl_impersonate_path=.curl-impersonate -Dgit_commit=$(git rev-parse --short ${{ github.sha }})

      - name: rename
        run: mv zig-out/bin/lightpanda lightpanda-${{ matrix.arch }}-${{ matrix.target_os }}

      - name: upload release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: lightpanda-${{ matrix.arch }}-${{ matrix.target_os }}
          tag: nightly
          makeLatest: true
